---
name: "cmerror_rule"
pack: "demo"
description: "Execute Python script when cmerror message received"
enabled: true
trigger:
  type: "demo.cmerror_trigger"
action:
  ref: "core.local"
  parameters:
    cmd: "source /opt/stackstorm/virtualenvs/demo/bin/activate && python3 /opt/stackstorm/packs/demo/scripts/logic.py '{{trigger.message}}'"
    timeout: 900 
