demo:
  type: object
  title: Demo Pack Config Schema
  description: Configuration schema for the demo pack
  properties:
    bootstrap_servers:
      type: string
      default: "localhost:9092"
      description: "Kafka bootstrap servers"
    group_id:
      type: string
      default: "st2_demo"
      description: "Kafka consumer group ID"
    topic:
      type: string
      default: "demo_topic"
      description: "Kafka topic name"
    message_sensor:
      type: object
      properties:
        bootstrap_servers:
          type: string
          default: "localhost:9092"
        topics:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              group_id:
                type: string
              trigger:
                type: string
          default:
            - name: "cmerror"
              group_id: "st2_cmerror"
              trigger: "demo.cmerror_trigger"
      additionalProperties: false
  additionalProperties: false
  required:
    - bootstrap_servers
    - group_id
    - topic